name: Erlang CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Erlang/OTP & Rebar3
        uses: erlef/setup-beam@v1
        with:
          otp-version: 25
          rebar3-version: 3.20.0
          install-hex: true
          install-rebar: true
          hexpm-mirrors: https://builds.hex.pm

      - name: Verify Dependencies
        run: rebar3 get-deps

      - name: Compile
        run: rebar3 compile || (echo "Compilation failed"; exit 1)

      - name: Run Tests
        run: rebar3 eunit || (echo "Tests failed"; exit 1)
