name: CI Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs nightly at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Erlang/OTP and Rebar3
        uses: erlef/setup-beam@v1
        with:
          otp-version: '25'
          rebar3-version: '3.20.0'

      - name: Install dependencies
        run: rebar3 get-deps

      - name: Compile project
        run: rebar3 compile

      - name: Run tests
        run: rebar3 eunit

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image with provenance
        run: |
          docker buildx build --platform linux/amd64 --file Dockerfile \
            --tag ${{ secrets.DOCKER_USERNAME }}/ioc2rpz:latest \
            --attest type=provenance,mode=max \
            --sbom=true \
            --push .
      
      - name: Inspect provenance
        run: |
          docker buildx imagetools inspect ${{ secrets.DOCKER_USERNAME }}/ioc2rpz:latest \
            --format "{{ json .Provenance.SLSA }}"
