name: CI Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs nightly at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check repository structure
        run: ls -R

      - name: Check file naming consistency
        run: find . -iname "*.erl"

      - name: Set up Erlang/OTP and Rebar3
        uses: erlef/setup-beam@v1
        with:
          otp-version: '25'
          rebar3-version: '3.20.0'

      - name: Check Erlang and Rebar3 versions
        run: |
          erl -version
          rebar3 version

      - name: Install dependencies
        run: rebar3 get-deps || (test -f rebar3.crashdump && cat rebar3.crashdump || true; exit 1)

      - name: Compile project with debugging
        run: |
          ERL_AFLAGS="-DTEST_ENV" rebar3 compile || (test -f rebar3.crashdump && cat rebar3.crashdump || true; exit 1)

      - name: Run tests
        run: rebar3 eunit || (test -f rebar3.crashdump && cat rebar3.crashdump || true; exit 1)

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image with provenance
        run: |
          docker buildx build --platform linux/amd64 --file Dockerfile \
            --tag ${{ secrets.DOCKER_USERNAME }}/ioc2rpz:latest \
            --attest type=provenance,mode=max \
            --sbom=true \
            --push .
      
      - name: Inspect provenance
        run: |
          docker buildx imagetools inspect ${{ secrets.DOCKER_USERNAME }}/ioc2rpz:latest \
            --format "{{ json .Provenance.SLSA }}"
